const rest = "http://localhost:2026/api/"
const classification = rest+"classification/"
const auth= rest+"auth/"
exports.departments = classification+"departments"
exports.login = auth+ "login"
exports.tutor =rest+"tutor"
exports.company=auth+"company"
exports.student=auth+"student"
